### ISSUE TITLE
Is changing ENV threadsafe?

### ISSUE THREAD

**Issue by zmoazeni** [grosser/cc-amend#1]
Hi there,

I'm mainly curious and thought I'd ask in case I was missing something.

The thin server starts up in a multithreaded way with [`--threaded`](https://github.com/grosser/cc-amend/blob/1b671ff9f0b370a6813b8cded3300eb4677e8cd7/Procfile) but the code itself will [swap out the `ENV["CODECLIMATE_REPO_TOKEN"]`](https://github.com/grosser/cc-amend/blob/1b671ff9f0b370a6813b8cded3300eb4677e8cd7/app.rb#L38).

Does that ENV swapping make the code unsafe for threads?

I was wondering if that method should be synchronized with a Mutex for the process.

**Comment by grosser** [comment]
yep, won't work in multiple threads ... go to put a mutex around that
